-- Criação da tabela de Usuários
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    senha VARCHAR(255),
    role VARCHAR(50)
);

-- Criação da tabela de Notícias
CREATE TABLE noticias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    capa_url VARCHAR(255)
);

-- Criação da tabela de Podcasts
CREATE TABLE podcasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    capa_url VARCHAR(255),
    audio_url VARCHAR(255)
);